# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: next-ingress
# spec:
#   rules:
#     - host: example.com
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: next-service
#                 port:
#                   number: 80
